### ISSUE TITLE
Update to V6 beta version (NET-Core)

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Template-NET-core#1]
Update State Web Template to the  latest 6.0.8 version

**Comment by kkoryaka** [comment]
@carterm you can go ahead and update this one.

**Comment by yesenia-gtz** [comment]
**To be completed by:**
[v6 Production release](https://github.com/Office-of-Digital-Services/California-State-Web-Template/milestone/3)
 Due by December 16, 2022 
Final release of State Web Template.

**Comment by yesenia-gtz** [comment]
This is completed

**Comment by carterm** [comment]
.Net Core and MVC versions will be combined here...

https://github.com/Office-of-Digital-Services/California-State-Web-Template-NET-Core-MVC

**Comment by extinah** [comment]
It's combined, so closing this card. 
Combined here: https://github.com/Office-of-Digital-Services/California-State-Web-Template-MVC/issues/2
